name: Main Workflow

on:
  push:
    branches: ['main']
  release:
    types: [created]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-date-time.yml
    with:
      filename: 'current_date_time.txt'
  
